package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"giphy/challenge/src/infrastructure/graphql/model"
	"giphy/challenge/src/infrastructure/graphql/model/mappers"
	"giphy/challenge/src/infrastructure/graphql/server/config"
)

// CreateGif is the resolver for the createGIF field.
func (r *mutationResolver) CreateGif(ctx context.Context, input *model.GIFInput) (*model.Gif, error) {
	result, err := r.GIFUseCase.Create(ctx, mappers.GIFInputModelToEntity(input))

	if err != nil {
		return nil, err
	}

	return mappers.GIFEntityToModel(result), nil
}

// Mutation returns config.MutationResolver implementation.
func (r *Resolver) Mutation() config.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
