version: '3.9'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db-config:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    links:
      - "mongodb:database"
    security_opt:
      - no-new-privileges:false
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_GIF_DATABASE=${MONGO_GIF_DATABASE}
      - MONGO_GIF_COLLECTION=${MONGO_GIF_COLLECTION}
      - HTTP_PLATFORM_PORT=${HTTP_PLATFORM_PORT}

volumes:
  db-config:
