// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Gif struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	URL       string   `json:"URL"`
	User      string   `json:"user"`
	Tags      []string `json:"tags"`
	CreatedAt string   `json:"createdAt"`
}

type GIFInput struct {
	Content string   `json:"content"`
	Name    string   `json:"name"`
	User    string   `json:"user"`
	Tags    []string `json:"tags"`
}

type GIFPagination struct {
	Page        int    `json:"page"`
	RowsPerPage int    `json:"rowsPerPage"`
	TotalRows   int    `json:"totalRows"`
	Results     []*Gif `json:"results"`
}

type GIFSearchInput struct {
	Query *string `json:"query,omitempty"`
	Page  int     `json:"page"`
}

type Mutation struct {
}

type Query struct {
}
